name: Bug Report
title: "[BUG]: "
description: File a bug report to help the project improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to fill out this bug report!
        ---
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also describe, what did you expect to happen?
      placeholder: Describe what happened!
      value: A bug happened!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk through it step by step.
      placeholder: Describe how!
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: browsers
    attributes:
      label: Browsers
      description: What browsers are you seeing the problem on?
      placeholder: A list of broswers!
      value: |
        - Safari
        - Safari for iOS
        - Chrome
        - Firefox for Android
        ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        ---
        ### Thanks for completing the form!
